language: go

services:
  - docker

script:
  - docker build -t vsliouniaev/helm-prom-test:latest .
  - docker run vsliouniaev/helm-prom-test

jobs:
  include:
    - stage: deploy latest to docker hub
      deploy:
        provider: script
        script: bash .ci/deploy
      on:
        branch: master