language: go

services:
  - docker

script:
  - docker build -t vsliouniaev/helm-prom-test --build-arg VERSION=$TRAVIS_TAG .
  - docker run vsliouniaev/helm-prom-test

jobs:
  include:
    - if: branch = master AND tag IS blank
      stage: build
    - if: branch = master AND tag IS present
      stage: push tag
      deploy:
        provider: script
        script: bash .ci/deploy $TRAVIS_TAG
