language: go

services:
  - docker

script:
  - docker build -t vsliouniaev/helm-prom-test .
  - docker run vsliouniaev/helm-prom-test

jobs:
  include:
    - stage: push to docker hub
      deploy:
        provider: script
        script: bash .ci/deploy
        on:
          branch: master
          tags: false
    - stage: push tag to docker hub
      deploy:
        provider: script
        script: bash .ci/deploy $TRAVIS_TAG
        on:
          tags: true
